"""
Decision Model

Represents the final AI decision.
"""

from dataclasses import dataclass, field


@dataclass(slots=True)
class Decision:
    """
    Final decision generated by the AI.
    """

    action: str

    confidence: float

    score: float

    reasons: list[str] = field(default_factory=list)

    bullish_factors: int = 0

    bearish_factors: int = 0

    neutral_factors: int = 0