"""
Evidence Model

Represents one AI signal generated by any intelligence engine.
"""

from dataclasses import dataclass


@dataclass(slots=True)
class Evidence:
    """
    One normalized trading signal.
    """

    source: str

    signal: str

    confidence: float

    weight: float

    score: float

    reason: str